# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

jobs:
  build:
    docker:
      - image: tooljet

    steps:
      - checkout
      - run:
          name: Build and Test
          command: |
            cd cypress-tests
            docker-compose up
            npm run cy:run

workflows:
  version: 2
  build:
    jobs:
      - build